#!/bin/bash

echo "------ HOOK START - BUILD -------"

DOCKER_HUB_NAME=nmtan/rdf4j
VERSION_LIST_FILE=versions
BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

function build_image(){
    if [ $#  -lt 1 ]; then
        # missing the damn tag
        return 0;
    fi

    tag_name="${1}"
    image_full_name="${DOCKER_HUB_NAME}:${tag_name}"
    if [ "${1}" == "latest" ]; then
        # Latest version - we do not need the version argument - latest version is defined in Dockerfile itself
        docker build --rm --build-arg BUILD_DATE="${BUILD_DATE}" \
            -t "${image_full_name}" .
    else
        docker build --rm --build-arg BUILD_DATE="${BUILD_DATE}" \
            --build-arg RDF4J_VERSION="${1}" \
            -t "${image_full_name}" .
    fi

    docker push "${image_full_name}"
}

while read -r tag; do
    echo "Building the image ${DOCKER_HUB_NAME}:${tag}"
    build_image "${tag}"
done < ${VERSION_LIST_FILE}

echo "------ HOOK END - BUILD -------"
